name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.saikrishna1904 }}
        password: ${{ secrets.Saikrishna@64 }}
        
    - name: Build the Docker image
      run: docker build . --file test.dockerfile --tag my-image-name:$(date +%s)
